name: 拉取 Astr 数据
on:
  workflow_dispatch:

jobs:
  sync-astr:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Astr plugin market
        run: |
          mkdir -p astr
          SRC_URL="https://github.com/AstrBotDevs/AstrBot_Plugins_Collection/raw/refs/heads/main/plugin_cache_original.json"
          
          # 计算哈希用于缓存控制
          HASH=$(curl -fsSL "$SRC_URL" | sha256sum | awk '{print $1}')
          
          # 拉取并保存
          curl -fsSL "$SRC_URL" -o "astr/index.${HASH}.json"
          cp "astr/index.${HASH}.json" astr/index.json
          echo "$HASH" > astr/version.txt

      - name: Upload Astr Artifact
        uses: actions/upload-artifact@v4
        with:
          name: astr-data
          path: astr/
          retention-days: 1
